/**
 * Generate a fresh BSV address dedicated to pitch registration fees.
 *
 * Run ONCE to provision the pitch receive address. The script:
 *   1. Generates a fresh PrivateKey
 *   2. Prints the WIF and address to stdout (NOT written to disk)
 *   3. Patches docs/brochure/pitch-config.json with the address
 *      (the WIF is never written anywhere — you copy it from the
 *      terminal into your .env.local manually)
 *
 * Usage:
 *   pnpm tsx scripts/generate-pitch-address.ts
 *
 * After running:
 *   1. Copy the WIF into ~/.env.local on the runner host as
 *      PITCH_RECEIVE_WIF=L… (private — never commit)
 *   2. Set PITCH_RECEIVE_ADDRESS in the runner shell to the
 *      address that was printed (matches what's now in pitch-config.json)
 *   3. Restart the swarm: `pnpm agents:swarm -- --team --bsvapi …`
 *   4. Push the updated pitch-config.json to deploy via Vercel
 *
 * Security: this script intentionally never writes the WIF to a
 * file. If you Ctrl+C before copying it, just run the script again
 * — fresh keys are cheap.
 */

import { PrivateKey } from '@bsv/sdk';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const PITCH_CONFIG_PATH = resolve('docs/brochure/pitch-config.json');

async function main() {
  const pk = PrivateKey.fromRandom();
  const wif = pk.toWif();
  const address = pk.toAddress();

  console.log('');
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  bMovies pitch receive address — generated', new Date().toISOString());
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('');
  console.log('  Address (public, safe to share):');
  console.log('    ' + address);
  console.log('');
  console.log('  WIF (PRIVATE — copy now, never written to disk):');
  console.log('    ' + wif);
  console.log('');
  console.log('───────────────────────────────────────────────────────────────');
  console.log('  Next steps:');
  console.log('    1. Copy the WIF above into ~/.env.local on the runner host:');
  console.log('         PITCH_RECEIVE_WIF=' + wif);
  console.log('    2. Export PITCH_RECEIVE_ADDRESS in the runner shell:');
  console.log('         export PITCH_RECEIVE_ADDRESS=' + address);
  console.log('    3. Commit + push the updated docs/brochure/pitch-config.json');
  console.log('       (the address is being patched in now — WIF stays in your terminal)');
  console.log('    4. Restart the swarm:');
  console.log('         pnpm agents:swarm -- --team --bsvapi https://www.bsvapi.com');
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('');

  // Patch pitch-config.json with the address only.
  const raw = await readFile(PITCH_CONFIG_PATH, 'utf8');
  const cfg = JSON.parse(raw) as Record<string, unknown>;
  cfg.receiveAddress = address;
  cfg.comment =
    'receiveAddress was generated by scripts/generate-pitch-address.ts on ' +
    new Date().toISOString().slice(0, 10) +
    '. The matching WIF lives in the runner host .env.local as PITCH_RECEIVE_WIF and is never committed.';
  await writeFile(PITCH_CONFIG_PATH, JSON.stringify(cfg, null, 2) + '\n');

  console.log('Patched ' + PITCH_CONFIG_PATH + ' with the new address.');
  console.log('Review the diff with `git diff docs/brochure/pitch-config.json`.');
  console.log('');
}

main().catch((err) => {
  console.error('generate-pitch-address failed:', err);
  process.exit(1);
});
